id: DomainTools_Check_Domain_Risk_Score_By_Iris_Tags
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: DomainTools Check Domain Risk Score By Iris Tags
description: This playbook will alert a user if a monitored set of domains, labeled
  by Iris Investigate tags, becomes high risk. To use it, tag domains in the Iris
  Investigate UI. Enter a comma-separated list of tags to monitor to the playbook
  input "dt_monitored_iris_tags" and run this playbook on a scheduled basis. It will
  add any new high risk domains (based on the threshold defined in this playbook)
  as indicators on the associated incident.
tags:
- Domaintools
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 89d688bd-2022-42de-86e8-e89f16fddd75
    type: start
    task:
      id: 89d688bd-2022-42de-86e8-e89f16fddd75
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ab1c0140-232a-4f9b-8f17-032bfe53def0
    type: regular
    task:
      id: ab1c0140-232a-4f9b-8f17-032bfe53def0
      version: -1
      name: Query Domains by Iris Tag(s)
      description: Pivot on connected infrastructure (IP, email, SSL), or import domains
        from Iris Investigate using a search hash. Retrieves up to 5000 domains at
        a time. Optionally attach the results to context with include_context=true.
      script: DomainTools Iris|||domaintoolsiris-pivot
      type: regular
      iscommand: true
      brand: DomainTools Iris
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      tagged_with_any:
        complex:
          root: inputs.dt_monitored_iris_tags
          transformers:
          - operator: trim
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 08cfdb90-ed08-4a4b-8cb4-a4d15eee3c10
    type: title
    description: 'Title'
    task:
      id: 08cfdb90-ed08-4a4b-8cb4-a4d15eee3c10
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b33df737-cba2-4c75-8ec0-60dd106fa207
    type: regular
    description: 'Manually Review High Risk Score Domains'
    task:
      id: b33df737-cba2-4c75-8ec0-60dd106fa207
      version: -1
      name: Manually Review High Risk Score Domains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    defaultassigneecomplex:
      simple: Analyst
    view: |-
      {
        "position": {
          "x": -400,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: cfeb1fe9-de0e-46b9-8307-a18a3ad5a1e2
    type: condition
    task:
      id: cfeb1fe9-de0e-46b9-8307-a18a3ad5a1e2
      version: -1
      name: Is there any Active and High Risk Score Domain?
      description: |-
        Checks if one number(float) as bigger than the other(float)
        Returns yes: if first > second
        Returns no: if first <= second
        Returns exception if one of the inputs is not a number
      scriptName: IsGreaterThan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    scriptarguments:
      first:
        simple: ${DomainTools.Pivots.PivotedDomains.Analytics.OverallRiskScore}
      second:
        simple: ${inputs.dt_min_riskscore_threshold}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: f9dd6ec0-6672-4116-8686-e0da296f1616
    type: regular
    task:
      id: f9dd6ec0-6672-4116-8686-e0da296f1616
      version: -1
      name: Add High Risk Domain to Indicator
      description: Sets Data for a Domain in the Indicator Table
      scriptName: SetIndicatorTableData
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      domaintools_data:
        complex:
          root: DomainTools.Pivots.PivotedDomains
          filters:
          - - operator: greaterThan
              left:
                value:
                  simple: DomainTools.Pivots.PivotedDomains.Analytics.OverallRiskScore
                iscontext: true
              right:
                value:
                  simple: inputs.dt_min_riskscore_threshold
                iscontext: true
          - - operator: isTrue
              left:
                value:
                  simple: DomainTools.Pivots.PivotedDomains.Registration.DomainStatus
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -390,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 034fc5cb-6f90-4c37-8154-b995643d1edd
    type: condition
    description: 'Should wait for an analyst review?'
    task:
      id: 034fc5cb-6f90-4c37-8154-b995643d1edd
      version: -1
      name: Should wait for an analyst review?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.should_wait_for_analyst_review
            iscontext: true
    view: |-
      {
        "position": {
          "x": -390,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "4_2_#default#": 0.57
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 830,
        "x": -400,
        "y": 50
      }
    }
  }
inputs:
- key: dt_min_riskscore_threshold
  value:
    simple: "70"
  required: true
  description: The minimum risk score threshold value to compare.
  playbookInputQuery: null
- key: dt_monitored_iris_tags
  value:
    simple: blocklist,good
  required: true
  description: |-
    The Iris tags to lookup. Values should be a comma separated value.
    e.g. (tag1,tag2)
  playbookInputQuery: null
- key: should_wait_for_analyst_review
  value:
    simple: "false"
  required: true
  description: Flags if users should wait for an analyst to review. Default is false.
    Value can be either true/false only.
  playbookInputQuery: null
outputs: []
fromversion: 6.9.0
