id: DomainTools_Iris_Tags
version: -1
name: DomainTools_Iris_Tags
starttaskid: "0"
description: ""
tasks:
  "0":
    id: "0"
    taskid: 15a9780b-4480-4304-8908-16a5e8b8563b
    type: start
    task:
      id: 15a9780b-4480-4304-8908-16a5e8b8563b
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": -100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: b85ab0d0-592d-4eee-8c7e-905fcfe69a4c
    type: regular
    task:
      id: b85ab0d0-592d-4eee-8c7e-905fcfe69a4c
      version: -1
      name: CheckTags
      description: Check DomainTools domain tags and if a tag is found mark incident
        as high severity
      scriptName: CheckTags
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      domain:
        simple: ${inputs.domain}
      domain_tags:
        simple: ${inputs.domain_tags}
      incident_id:
        simple: ${incident.id}
      malicious_tags:
        simple: ${lists.tags}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 240,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 67a6fbed-af34-434f-8b6e-6c7088e8cafe
    type: title
    task:
      id: 67a6fbed-af34-434f-8b6e-6c7088e8cafe
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: b5deb259-ef11-4315-8ce8-bc19986c8d67
    type: condition
    task:
      id: b5deb259-ef11-4315-8ce8-bc19986c8d67
      version: -1
      name: Check Domain has Tags
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.domain_tags
            iscontext: true
    view: |-
      {
        "position": {
          "x": 440,
          "y": 90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 805,
        "width": 580,
        "x": 240,
        "y": -100
      }
    }
  }
inputs:
- key: domain_tags
  value:
    simple: ${DomainTools.Domains.Analytics.Tags}
  required: false
  description: ""
outputs:
- contextPath: domain
  description: domain
  type: unknown
tests:
- DomainTools Iris - Test
fromversion: 4.1.0