id: DomainTools_Domain_Auto_Enrichment
version: -1
name: DomainTools_Domain_Auto_Enrichment
starttaskid: "0"
description: ""
tasks:
  "0":
    id: "0"
    taskid: 1d7e431e-9f49-4a0b-87be-51b6f41e6ee6
    type: start
    task:
      id: 1d7e431e-9f49-4a0b-87be-51b6f41e6ee6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: bef65bdc-1cdf-4ea1-8cc0-ad2ae2f9c78b
    type: condition
    task:
      id: bef65bdc-1cdf-4ea1-8cc0-ad2ae2f9c78b
      version: -1
      name: Do New Domain Enrichment?
      scriptName: CheckLastEnrichment
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "4"
    scriptarguments:
      last_enrichment:
        simple: ${DomainTools.Domains.LastEnriched}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 955a1960-17dc-44f1-8d00-27acf25e643f
    type: regular
    task:
      id: 955a1960-17dc-44f1-8d00-27acf25e643f
      version: -1
      name: Add to Indicator Table
      scriptName: SetIndicatorTableData
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      domain:
        simple: ${DomainTools.Domains}
      domaintools_data:
        simple: ${DomainTools.Domains}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 6c882f2a-e8ab-47e4-8a32-2db3ae436b7c
    type: regular
    task:
      id: 6c882f2a-e8ab-47e4-8a32-2db3ae436b7c
      version: -1
      name: Enrich Domain
      script: DomainTools Iris|||domain
      type: regular
      iscommand: true
      brand: DomainTools Iris
      description: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      domain:
        simple: ${Domain.Name}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -50,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 244d3a63-472e-40d6-82cd-79553ac42497
    type: title
    task:
      id: 244d3a63-472e-40d6-82cd-79553ac42497
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: a30c3455-1aba-45b4-8bb9-63e47866147d
    type: condition
    task:
      id: a30c3455-1aba-45b4-8bb9-63e47866147d
      version: -1
      name: Does the Domain context data exist?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: ${DomainTools
                accessor: Domains}
                transformers:
                - operator: uniq
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1175,
        "width": 880,
        "x": -50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- DomainTools Iris - Test
fromversion: 4.1.0
